### ISSUE TITLE
Nightlight schedule shows wrong time format

### ISSUE THREAD

**Issue by D0J0P** [elementary/wingpanel-indicator-nightlight#37]
I have my time format set to AM/PM, and nightlight displays the time in the schedule as 24h time. 
![screenshot from 2018-10-17 00 08 44](https://user-images.githubusercontent.com/19495660/47061752-dd259380-d1a0-11e8-8528-663acb7001b4.png)

**Comment by ryonakano** [comment]
@D0J0P I think this should be fixed with https://github.com/elementary/granite/pull/222

**Comment by danrabbit** [comment]
Closing since the time picker widget sets its own time format and changing that is outside the scope of this particular code repo

**Comment by D0J0P** [comment]
> @D0J0P I think this should be fixed with [elementary/granite#222](https://github.com/elementary/granite/pull/222)

Nope, not yet. Should I report it to Granite?

**Comment by jeremypw** [comment]
@D0J0P This could be due to a mistranslation of the time format string either in Granite or, if the affected project has its own time format code, in that project.  I have come across this problem before.  Which language do you use?

**Comment by D0J0P** [comment]
The language is set to English US, but the place is Canada.

**Comment by jeremypw** [comment]
I did get some weirdness with a vanilla install where the time formats did not match but after recompiling and installing Granite, wingpanel-indicator-datetime and switchboard-plug-datetime (in that order) from master source, it all seems to work OK.  There isn't any problem with time format translations in the en_CA.po.
