### ISSUE TITLE
Night Light remains active after sleep

### ISSUE THREAD

**Issue by stsdc** [elementary/wingpanel-indicator-nightlight#49]
After wakening up when Night Light is out of time period of activation screen remains warm coloured. Switching monitor on/off fixes this.

```
System:    Host: desktop Kernel: 5.1.12-050112-generic x86_64 bits: 64 Desktop: Gnome
           Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASRock model: B450 Gaming-ITX/ac serial: N/A UEFI: American Megatrends v: P3.30 date: 05/17/2019
CPU:       Quad core AMD Ryzen 5 2400G with Radeon Vega Graphics (-MT-MCP-) speed/max: 1534/3600 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: AMD RAVEN (DRM 3.30.0, 5.1.12-050112-generic, LLVM 8.0.0)
           version: 4.5 Mesa 19.1.0 - padoka PPA
Network:   Card-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
           Card-2: Intel I211 Gigabit Network Connection driver: igb
Drives:    HDD Total Size: 1628.3GB (5.0% used)
Info:      Processes: 289 Uptime: 1 day Memory: 2333.5/5946.4MB Client: Shell (zsh) inxi: 2.3.56 
```

**Comment by peteruithoven** [comment]
Nightlight depends on the color plugin of the gnome-settings-daemon for the actual color changing functionality. The settings and the indicator merely configure it. 
This doesn't sounds like a configuration issue so I'm afraid you'll need to open an issue here:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon

I'd be curious whether you could also correct the color by rebooting the daemon this plugin creates. You can do that by running `killall gsd-color`.
Using applications like Monitor or `htop` you can see this daemon/process listed as: 
`/usr/lib/gnome-settings-daemon/gsd-color`
