### ISSUE TITLE
[Juno] Nightlight stops working after suspend/resume

### ISSUE THREAD

**Issue by dennismayr** [elementary/wingpanel-indicator-nightlight#51]
Nightlight works after logging into the user session when turning the computer on, but stops working after sleeping & resuming (e.g. closing laptop).

No nightlight icon on wingpanel, no color temperature modification, no way of activating it manually (going to the control panel and disabling/enabling it by hand does not work).

**Comment by dennismayr** [comment]
Well, I've run into this: #47.
The title said that it "ocacionally" didn't work, but the case is "always", hence my failure to fin it the first time.
If said bug was closed because it wasn't about the indicator itself, how / where can the bug be reported? Which package would be appropriate?

**Comment by peteruithoven** [comment]
The repo reported at: https://github.com/elementary/wingpanel-indicator-nightlight/issues/47#issuecomment-490011872

Also closing this one as out of scope.
