### ISSUE TITLE
Change toggle to a snooze

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-nightlight#9]
>**Snooze Night Light**  (O—)
>
> ————————O———
>
>Night Light Settings…

And if we want to get real fancy:

>**Snooze Night Light** (—O)
>
>_Snoozed until sunset_
>
>Night Light Settings…

**Comment by cassidyjames** [comment]
The snooze text should probably be a dim label (**no italics!**), and maybe even `<small>`.

**Comment by danrabbit** [comment]
Here's a bad GIMP mockup:

![screenshot from 2017-12-13 14 53 45](https://user-images.githubusercontent.com/7277719/34006886-c267783e-e0b4-11e7-8d29-4f26af01c1c9.png)
